name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: joshbainbridge/blue-noise-service
          tag_with_ref: true
          target: server
